import type { Config } from './types'

export const SAMPLE_SCRIPT = `# One message per line. Paste the JSON from the AI prompt (Help tab) here instead if you like.
# "name: text" = a specific user, plain text = a random viewer, lines starting with ! are events.
yo chat, is this the new update?
[mod] nightbot: Welcome! Type !discord to join the community
no way he's actually doing it
LETS GOOO {e:hype}
!sub coolguy_92 prime 12 -- love the stream!
+0.4 KEKW KEKW KEKW
clip it CLIP IT
!gifts bigspender_ttv 5
[vip] jess_plays: hydrate {streamer}!!
!highlight can you say hi to my little brother? its his birthday
!burst 15 W
`

export const DEFAULT_CONFIG: Config = {
  seed: 'twitchsim',
  mode: 'mixed',
  script: SAMPLE_SCRIPT,
  mood: 'gaming',
  streamerName: 'Streamer',
  streamerLogin: '',
  viewerName: '',
  gameName: 'the game',
  language: 'en',
  scriptUsersRandom: true,
  scriptGapMultiplier: 4,
  streamerChats: true,
  streamerColor: '',
  messagesPerMinute: 90,
  pacing: 'natural',
  burstiness: 0.5,
  reactionMoments: 0.5,
  startDelayMs: 0,
  prefillSec: 0,
  durationSec: 30,
  durationAuto: true,
  tailSec: 3,
  subsRate: 0.5,
  giftsRate: 0.4,
  raidsRate: 0.15,
  cheersRate: 0.4,
  firstTimeRate: 0.4,
  highlightRate: 0.4,
  replyRate: 0.5,
  deleteRate: 0.3,
  announcementRate: 0.3,
  actionsRate: 0.15,
  mentionsRate: 0.5,
  powerUpsRate: 0.15,
  rewardRate: 0.2,
  systemNotices: true,
  welcomeMessage: true,
  chatterPoolSize: 120,
  customColorRatio: 0.45,
  subRatio: 0.35,
  primeRatio: 0.2,
  modCount: 3,
  vipCount: 4,
  bitsBadgeRatio: 0.12,
  gifterBadgeRatio: 0.1,
  eventBadgeRatio: 0.35,
  botsEnabled: true,
  customNames: '',
  customNamesOnly: false,
  localizedNamesRatio: 0.03,
  channelSubBadgeStyle: 'generated',
  loadedChannel: '',
  customBadges: [],
  customEmotes: [],
  badgeRadius: 0.14,
  badgeFit: 'cover',
  useCustomEmotesInFiller: true,
  emoteDensity: 0.5,
  useTwitchEmotes: true,
  use7tvEmotes: true,
  useChannelEmotes: true,
  animatedEmotes: true,
  chatStyle: 'twitch-dark',
  theme: 'dark',
  bgColor: '#18181b',
  bgOpacity: 1,
  cornerRadius: 0,
  textShadow: true,
  textOutline: 0,
  fontSize: 'default',
  fontScale: 1,
  fontFamily: 'Inter',
  width: 340,
  height: 600,
  paddingX: 16,
  paddingBottom: 10,
  timestamps: false,
  alternateBg: false,
  readableColors: true,
  showBadges: true,
  boldNames: true,
  animation: 'slide-up',
  animationMs: 220,
  fadeTopEdge: 0,
  modView: false,
  hypeTrain: false,
  exportScale: 3,
  exportFps: 30,
  exportFormat: 'webm-alpha',
  exportTransparent: true,
  exportBg: '#000000',
  frameW: 1920,
  frameH: 1080,
  framePreset: 'chat',
  anchor: 'br',
  marginX: 40,
  marginY: 40,
}

export const FRAME_PRESETS: Record<Config['framePreset'], { w: number; h: number; label: string }> = {
  chat: { w: 0, h: 0, label: 'Chat only (tight)' },
  '1080p': { w: 1920, h: 1080, label: '1080p (1920×1080)' },
  '1440p': { w: 2560, h: 1440, label: '1440p (2560×1440)' },
  '4k': { w: 3840, h: 2160, label: '4K UHD (3840×2160)' },
  vertical: { w: 1080, h: 1920, label: 'Vertical 9:16 (1080×1920)' },
  custom: { w: 0, h: 0, label: 'Custom' },
}
