import type { Config } from './types'

export const SAMPLE_SCRIPT = `coolguy_92: yo chat, is this the new update?
[mod] nightbot: Welcome! Type !discord to join the community
no way he's actually doing it
jess_plays: LETS GOOO PogChamp
KEKW KEKW KEKW
clip it CLIP IT
[sub] xX_shadow_Xx: hydrate {streamer}!!
W
W W
that was insane
`

export const DEFAULT_CONFIG: Config = {
  seed: 'twitchsim',
  mode: 'mixed',
  script: SAMPLE_SCRIPT,
  mood: 'general',
  streamerName: 'Streamer',
  streamerLogin: '',
  viewerName: '',
  gameName: 'the game',
  language: 'en',
  scriptUsersRandom: true,
  scriptGapMultiplier: 4,
  fillerFromScript: false,
  streamerChats: true,
  streamerColor: '',
  messagesPerMinute: 90,
  pacing: 'natural',
  burstiness: 0.5,
  reactionMoments: 0.5,
  startDelayMs: 0,
  prefillSec: 0,
  durationSec: 30,
  durationAuto: true,
  tailSec: 3,
  subsRate: 0.5,
  giftsRate: 0.4,
  raidsRate: 0.15,
  cheersRate: 0.4,
  firstTimeRate: 0.4,
  highlightRate: 0.4,
  replyRate: 0.5,
  deleteRate: 0.3,
  announcementRate: 0.3,
  actionsRate: 0.15,
  mentionsRate: 0.5,
  powerUpsRate: 0, // giant emotes / message effects look like a glitch if you don't know Twitch power-ups: opt-in
  rewardRate: 0.2,
  systemNotices: true,
  welcomeMessage: true,
  chatterPoolSize: 120,
  customColorRatio: 0.45,
  subRatio: 0.35,
  primeRatio: 0.2,
  modCount: 3,
  vipCount: 4,
  bitsBadgeRatio: 0.12,
  gifterBadgeRatio: 0.1,
  eventBadgeRatio: 0.35,
  badgePool: ['moderator', 'vip', 'broadcaster', 'subscriber', 'founder', 'premium', 'turbo', 'partner', 'bits', 'sub-gifter', 'hype-train', 'predictions', 'events', 'no_av'],
  botsEnabled: true,
  customNames: '',
  customNamesOnly: false,
  localizedNamesRatio: 0.03,
  channelSubBadgeStyle: 'generated',
  loadedChannel: '',
  customBadges: [],
  customEmotes: [],
  customAvatars: [],
  avatarMode: 'off',
  avatarShape: 'circle',
  badgeRadius: 0.14,
  badgeFit: 'cover',
  useCustomEmotesInFiller: true,
  emoteDensity: 0.25,
  useTwitchEmotes: true,
  use7tvEmotes: true,
  useChannelEmotes: true,
  animatedEmotes: true,
  chatStyle: 'twitch-dark',
  theme: 'dark',
  bgColor: '#18181b',
  bgOpacity: 1,
  cornerRadius: 0,
  textShadow: true,
  textOutline: 0,
  fontSize: 'default',
  fontScale: 1,
  letterSpacing: 0,
  fontFamily: 'Inter',
  width: 340,
  height: 600,
  paddingX: 16,
  paddingBottom: 10,
  timestamps: false,
  alternateBg: false,
  readableColors: true,
  nameColorMode: 'twitch',
  nameColorPalette: ['#FF0000', '#0000FF', '#008000', '#B22222', '#FF7F50', '#9ACD32', '#FF4500', '#2E8B57', '#DAA520', '#D2691E', '#5F9EA0', '#1E90FF', '#FF69B4', '#8A2BE2', '#00FF7F'],
  showBadges: true,
  boldNames: true,
  animation: 'slide-up',
  animationMs: 220,
  easePreset: 'smooth',
  easeCurve: [0.22, 1, 0.36, 1],
  easeKeyframes: '',
  fadeTopEdge: 0,
  modView: false,
  hypeTrain: false,
  exportScale: 3,
  exportFps: 30,
  exportFormat: 'webm-alpha',
  exportTransparent: true,
  exportBg: '#000000',
  frameW: 1920,
  frameH: 1080,
  framePreset: 'chat',
  anchor: 'c',
  marginX: 40,
  marginY: 40,
}

export const FRAME_PRESETS: Record<Config['framePreset'], { w: number; h: number; label: string }> = {
  chat: { w: 0, h: 0, label: 'Chat only' },
  '1080p': { w: 1920, h: 1080, label: '1080p' },
  '1440p': { w: 2560, h: 1440, label: '1440p' },
  '4k': { w: 3840, h: 2160, label: '4K' },
  vertical: { w: 1080, h: 1920, label: 'Vertical 9:16' },
  custom: { w: 0, h: 0, label: 'Custom' },
}
